# Generated by Django 5.1.6 on 2025-02-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extended_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('owner', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/cafes/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorycafe',
        ),
        migrations.AddField(
            model_name='product',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cafe'),
        ),
        migrations.DeleteModel(
            name='CategoryCafe',
        ),
    ]
